package com.loyalcraft.constants

object HelperUtility {
  val FORWARD_SLASH = "/"
  val SPACE = " "
  val UNDERSCORE = "_"
  val EMPTY_STRING = ""
  val COMMA = ","
  val PERCENTAGE = "%"
  val DOT = "."
  val DOLLAR = "$"
  val AMPERSAND = "&"
  val PLUS = "+"
  val COLON = ":"
  val SEMI_COLON = ";"
  val EQUAL = "="
  val QUESTION_MARK = "?"
  val AT = "@"
  val HASH = "#"
  val OPENING_BRACES = "{"
  val CLOSING_BRACES = "}"
  val ANTI_SLASH = "\\"
  val LOWER = "<"
  val GREATER = ">"
  val CIRCUMFLEX = "^"
  val OPENING_SQUARE_BRACKETS = "["
  val CLOSING_SQUARE_BRACKETS = "]"
  val OR_LOGIC = "|"
  val SIGN = "~"
}
